use std::collections::HashMap;

pub fn dbc_name_map() -> HashMap<&'static str, &'static str> {
    HashMap::from([
        ("achievement.dbc", "Achievement.dbc"),
        ("footprinttextures.dbc", "FootprintTextures.dbc"),
        ("namesprofanity.dbc", "NamesProfanity.dbc"),
        ("spellshapeshiftform.dbc", "SpellShapeshiftForm.dbc"),
        ("achievement_category.dbc", "Achievement_Category.dbc"),
        ("footstepterrainlookup.dbc", "FootstepTerrainLookup.dbc"),
        ("namesreserved.dbc", "NamesReserved.dbc"),
        ("spellvisual.dbc", "SpellVisual.dbc"),
        ("achievement_criteria.dbc", "Achievement_Criteria.dbc"),
        ("gmsurveyanswers.dbc", "GMSurveyAnswers.dbc"),
        ("objecteffect.dbc", "ObjectEffect.dbc"),
        ("spellvisualeffectname.dbc", "SpellVisualEffectName.dbc"),
        ("animationdata.dbc", "AnimationData.dbc"),
        ("gmsurveycurrentsurvey.dbc", "GMSurveyCurrentSurvey.dbc"),
        ("objecteffectgroup.dbc", "ObjectEffectGroup.dbc"),
        ("spellvisualkit.dbc", "SpellVisualKit.dbc"),
        ("areagroup.dbc", "AreaGroup.dbc"),
        ("gmsurveyquestions.dbc", "GMSurveyQuestions.dbc"),
        ("objecteffectmodifier.dbc", "ObjectEffectModifier.dbc"),
        ("spellvisualkitareamodel.dbc", "SpellVisualKitAreaModel.dbc"),
        ("areapoi.dbc", "AreaPOI.dbc"),
        ("gmsurveysurveys.dbc", "GMSurveySurveys.dbc"),
        ("objecteffectpackage.dbc", "ObjectEffectPackage.dbc"),
        (
            "spellvisualkitmodelattach.dbc",
            "SpellVisualKitModelAttach.dbc",
        ),
        ("areatable.dbc", "AreaTable.dbc"),
        ("gmticketcategory.dbc", "GMTicketCategory.dbc"),
        ("objecteffectpackageelem.dbc", "ObjectEffectPackageElem.dbc"),
        (
            "spellvisualprecasttransitions.dbc",
            "SpellVisualPrecastTransitions.dbc",
        ),
        ("areatrigger.dbc", "AreaTrigger.dbc"),
        ("gameobjectartkit.dbc", "GameObjectArtKit.dbc"),
        ("overridespelldata.dbc", "OverrideSpellData.dbc"),
        ("stableslotprices.dbc", "StableSlotPrices.dbc"),
        ("attackanimkits.dbc", "AttackAnimKits.dbc"),
        ("gameobjectdisplayinfo.dbc", "GameObjectDisplayInfo.dbc"),
        ("package.dbc", "Package.dbc"),
        ("startup_strings.dbc", "Startup_Strings.dbc"),
        ("attackanimtypes.dbc", "AttackAnimTypes.dbc"),
        ("gametables.dbc", "GameTables.dbc"),
        ("pagetextmaterial.dbc", "PageTextMaterial.dbc"),
        ("stationery.dbc", "Stationery.dbc"),
        ("auctionhouse.dbc", "AuctionHouse.dbc"),
        ("gametips.dbc", "GameTips.dbc"),
        ("paperdollitemframe.dbc", "PaperDollItemFrame.dbc"),
        ("stringlookups.dbc", "StringLookups.dbc"),
        ("bankbagslotprices.dbc", "BankBagSlotPrices.dbc"),
        ("gemproperties.dbc", "GemProperties.dbc"),
        ("particlecolor.dbc", "ParticleColor.dbc"),
        ("summonproperties.dbc", "SummonProperties.dbc"),
        ("bannedaddons.dbc", "BannedAddOns.dbc"),
        ("glyphproperties.dbc", "GlyphProperties.dbc"),
        ("petpersonality.dbc", "PetPersonality.dbc"),
        ("talent.dbc", "Talent.dbc"),
        ("barbershopstyle.dbc", "BarberShopStyle.dbc"),
        ("glyphslot.dbc", "GlyphSlot.dbc"),
        ("petitiontype.dbc", "PetitionType.dbc"),
        ("talenttab.dbc", "TalentTab.dbc"),
        ("battlemasterlist.dbc", "BattlemasterList.dbc"),
        ("groundeffectdoodad.dbc", "GroundEffectDoodad.dbc"),
        ("powerdisplay.dbc", "PowerDisplay.dbc"),
        ("taxinodes.dbc", "TaxiNodes.dbc"),
        ("camerashakes.dbc", "CameraShakes.dbc"),
        ("groundeffecttexture.dbc", "GroundEffectTexture.dbc"),
        ("pvpdifficulty.dbc", "PvpDifficulty.dbc"),
        ("taxipath.dbc", "TaxiPath.dbc"),
        ("cfg_categories.dbc", "Cfg_Categories.dbc"),
        ("helmetgeosetvisdata.dbc", "HelmetGeosetVisData.dbc"),
        ("questfactionreward.dbc", "QuestFactionReward.dbc"),
        ("taxipathnode.dbc", "TaxiPathNode.dbc"),
        ("cfg_configs.dbc", "Cfg_Configs.dbc"),
        ("holidaydescriptions.dbc", "HolidayDescriptions.dbc"),
        ("questinfo.dbc", "QuestInfo.dbc"),
        ("teamcontributionpoints.dbc", "TeamContributionPoints.dbc"),
        ("charbaseinfo.dbc", "CharBaseInfo.dbc"),
        ("holidaynames.dbc", "HolidayNames.dbc"),
        ("questsort.dbc", "QuestSort.dbc"),
        ("terraintype.dbc", "TerrainType.dbc"),
        ("charhairgeosets.dbc", "CharHairGeosets.dbc"),
        ("holidays.dbc", "Holidays.dbc"),
        ("questxp.dbc", "QuestXP.dbc"),
        ("terraintypesounds.dbc", "TerrainTypeSounds.dbc"),
        ("charhairtextures.dbc", "CharHairTextures.dbc"),
        ("item.dbc", "Item.dbc"),
        ("randproppoints.dbc", "RandPropPoints.dbc"),
        ("totemcategory.dbc", "TotemCategory.dbc"),
        ("charsections.dbc", "CharSections.dbc"),
        ("itembagfamily.dbc", "ItemBagFamily.dbc"),
        ("resistances.dbc", "Resistances.dbc"),
        ("transportanimation.dbc", "TransportAnimation.dbc"),
        ("charstartoutfit.dbc", "CharStartOutfit.dbc"),
        ("itemclass.dbc", "ItemClass.dbc"),
        ("scalingstatdistribution.dbc", "ScalingStatDistribution.dbc"),
        ("transportphysics.dbc", "TransportPhysics.dbc"),
        ("chartitles.dbc", "CharTitles.dbc"),
        ("itemcondextcosts.dbc", "ItemCondExtCosts.dbc"),
        ("scalingstatvalues.dbc", "ScalingStatValues.dbc"),
        ("transportrotation.dbc", "TransportRotation.dbc"),
        ("charvariations.dbc", "CharVariations.dbc"),
        ("itemdisplayinfo.dbc", "ItemDisplayInfo.dbc"),
        ("screeneffect.dbc", "ScreenEffect.dbc"),
        ("uisoundlookups.dbc", "UISoundLookups.dbc"),
        (
            "characterfacialhairstyles.dbc",
            "CharacterFacialHairStyles.dbc",
        ),
        ("itemextendedcost.dbc", "ItemExtendedCost.dbc"),
        ("servermessages.dbc", "ServerMessages.dbc"),
        ("unitblood.dbc", "UnitBlood.dbc"),
        ("chatchannels.dbc", "ChatChannels.dbc"),
        ("itemgroupsounds.dbc", "ItemGroupSounds.dbc"),
        ("sheathesoundlookups.dbc", "SheatheSoundLookups.dbc"),
        ("unitbloodlevels.dbc", "UnitBloodLevels.dbc"),
        ("chatprofanity.dbc", "ChatProfanity.dbc"),
        ("itemlimitcategory.dbc", "ItemLimitCategory.dbc"),
        ("skillcostsdata.dbc", "SkillCostsData.dbc"),
        ("vehicle.dbc", "Vehicle.dbc"),
        ("chrclasses.dbc", "ChrClasses.dbc"),
        ("itempetfood.dbc", "ItemPetFood.dbc"),
        ("skillline.dbc", "SkillLine.dbc"),
        ("vehicleseat.dbc", "VehicleSeat.dbc"),
        ("chrraces.dbc", "ChrRaces.dbc"),
        ("itempurchasegroup.dbc", "ItemPurchaseGroup.dbc"),
        ("skilllineability.dbc", "SkillLineAbility.dbc"),
        ("vehicleuiindseat.dbc", "VehicleUIIndSeat.dbc"),
        ("cinematiccamera.dbc", "CinematicCamera.dbc"),
        ("itemrandomproperties.dbc", "ItemRandomProperties.dbc"),
        ("skilllinecategory.dbc", "SkillLineCategory.dbc"),
        ("vehicleuiindicator.dbc", "VehicleUIIndicator.dbc"),
        ("cinematicsequences.dbc", "CinematicSequences.dbc"),
        ("itemrandomsuffix.dbc", "ItemRandomSuffix.dbc"),
        ("skillraceclassinfo.dbc", "SkillRaceClassInfo.dbc"),
        ("videohardware.dbc", "VideoHardware.dbc"),
        ("creaturedisplayinfo.dbc", "CreatureDisplayInfo.dbc"),
        ("itemset.dbc", "ItemSet.dbc"),
        ("skilltiers.dbc", "SkillTiers.dbc"),
        ("vocaluisounds.dbc", "VocalUISounds.dbc"),
        (
            "creaturedisplayinfoextra.dbc",
            "CreatureDisplayInfoExtra.dbc",
        ),
        ("itemsubclass.dbc", "ItemSubClass.dbc"),
        ("soundambience.dbc", "SoundAmbience.dbc"),
        ("wmoareatable.dbc", "WMOAreaTable.dbc"),
        ("creaturefamily.dbc", "CreatureFamily.dbc"),
        ("itemsubclassmask.dbc", "ItemSubClassMask.dbc"),
        ("soundemitters.dbc", "SoundEmitters.dbc"),
        ("weaponimpactsounds.dbc", "WeaponImpactSounds.dbc"),
        ("creaturemodeldata.dbc", "CreatureModelData.dbc"),
        ("itemvisualeffects.dbc", "ItemVisualEffects.dbc"),
        ("soundentries.dbc", "SoundEntries.dbc"),
        ("weaponswingsounds2.dbc", "WeaponSwingSounds2.dbc"),
        ("creaturemovementinfo.dbc", "CreatureMovementInfo.dbc"),
        ("itemvisuals.dbc", "ItemVisuals.dbc"),
        ("soundentriesadvanced.dbc", "SoundEntriesAdvanced.dbc"),
        ("weather.dbc", "Weather.dbc"),
        ("creaturesounddata.dbc", "CreatureSoundData.dbc"),
        ("lfgdungeonexpansion.dbc", "LFGDungeonExpansion.dbc"),
        ("soundfilter.dbc", "SoundFilter.dbc"),
        ("worldchunksounds.dbc", "WorldChunkSounds.dbc"),
        ("creaturespelldata.dbc", "CreatureSpellData.dbc"),
        ("lfgdungeongroup.dbc", "LFGDungeonGroup.dbc"),
        ("soundfilterelem.dbc", "SoundFilterElem.dbc"),
        ("worldmaparea.dbc", "WorldMapArea.dbc"),
        ("creaturetype.dbc", "CreatureType.dbc"),
        ("lfgdungeons.dbc", "LFGDungeons.dbc"),
        (
            "soundproviderpreferences.dbc",
            "SoundProviderPreferences.dbc",
        ),
        ("worldmapcontinent.dbc", "WorldMapContinent.dbc"),
        ("currencycategory.dbc", "CurrencyCategory.dbc"),
        ("languagewords.dbc", "LanguageWords.dbc"),
        ("soundsamplepreferences.dbc", "SoundSamplePreferences.dbc"),
        ("worldmapoverlay.dbc", "WorldMapOverlay.dbc"),
        ("currencytypes.dbc", "CurrencyTypes.dbc"),
        ("languages.dbc", "Languages.dbc"),
        ("soundwatertype.dbc", "SoundWaterType.dbc"),
        ("worldmaptransforms.dbc", "WorldMapTransforms.dbc"),
        ("dancemoves.dbc", "DanceMoves.dbc"),
        ("light.dbc", "Light.dbc"),
        ("spammessages.dbc", "SpamMessages.dbc"),
        ("worldsafelocs.dbc", "WorldSafeLocs.dbc"),
        ("deaththudlookups.dbc", "DeathThudLookups.dbc"),
        ("lightfloatband.dbc", "LightFloatBand.dbc"),
        ("spell.dbc", "Spell.dbc"),
        ("worldstateui.dbc", "WorldStateUI.dbc"),
        ("declinedword.dbc", "DeclinedWord.dbc"),
        ("lightintband.dbc", "LightIntBand.dbc"),
        ("spellcasttimes.dbc", "SpellCastTimes.dbc"),
        ("worldstatezonesounds.dbc", "WorldStateZoneSounds.dbc"),
        ("declinedwordcases.dbc", "DeclinedWordCases.dbc"),
        ("lightparams.dbc", "LightParams.dbc"),
        ("spellcategory.dbc", "SpellCategory.dbc"),
        ("wowerror_strings.dbc", "WowError_Strings.dbc"),
        ("destructiblemodeldata.dbc", "DestructibleModelData.dbc"),
        ("lightskybox.dbc", "LightSkybox.dbc"),
        ("spellchaineffects.dbc", "SpellChainEffects.dbc"),
        ("zoneintromusictable.dbc", "ZoneIntroMusicTable.dbc"),
        ("dungeonencounter.dbc", "DungeonEncounter.dbc"),
        ("liquidmaterial.dbc", "LiquidMaterial.dbc"),
        (
            "spelldescriptionvariables.dbc",
            "SpellDescriptionVariables.dbc",
        ),
        ("zonemusic.dbc", "ZoneMusic.dbc"),
        ("dungeonmap.dbc", "DungeonMap.dbc"),
        ("liquidtype.dbc", "LiquidType.dbc"),
        ("spelldifficulty.dbc", "SpellDifficulty.dbc"),
        ("gtbarbershopcostbase.dbc", "gtBarberShopCostBase.dbc"),
        ("dungeonmapchunk.dbc", "DungeonMapChunk.dbc"),
        (
            "loadingscreentaxisplines.dbc",
            "LoadingScreenTaxiSplines.dbc",
        ),
        ("spelldispeltype.dbc", "SpellDispelType.dbc"),
        ("gtchancetomeleecrit.dbc", "gtChanceToMeleeCrit.dbc"),
        ("durabilitycosts.dbc", "DurabilityCosts.dbc"),
        ("loadingscreens.dbc", "LoadingScreens.dbc"),
        ("spellduration.dbc", "SpellDuration.dbc"),
        ("gtchancetomeleecritbase.dbc", "gtChanceToMeleeCritBase.dbc"),
        ("durabilityquality.dbc", "DurabilityQuality.dbc"),
        ("lock.dbc", "Lock.dbc"),
        ("spelleffectcamerashakes.dbc", "SpellEffectCameraShakes.dbc"),
        ("gtchancetospellcrit.dbc", "gtChanceToSpellCrit.dbc"),
        ("emotes.dbc", "Emotes.dbc"),
        ("locktype.dbc", "LockType.dbc"),
        ("spellfocusobject.dbc", "SpellFocusObject.dbc"),
        ("gtchancetospellcritbase.dbc", "gtChanceToSpellCritBase.dbc"),
        ("emotestext.dbc", "EmotesText.dbc"),
        ("mailtemplate.dbc", "MailTemplate.dbc"),
        ("spellicon.dbc", "SpellIcon.dbc"),
        ("gtcombatratings.dbc", "gtCombatRatings.dbc"),
        ("emotestextdata.dbc", "EmotesTextData.dbc"),
        ("map.dbc", "Map.dbc"),
        ("spellitemenchantment.dbc", "SpellItemEnchantment.dbc"),
        ("gtnpcmanacostscaler.dbc", "gtNPCManaCostScaler.dbc"),
        ("emotestextsound.dbc", "EmotesTextSound.dbc"),
        ("mapdifficulty.dbc", "MapDifficulty.dbc"),
        (
            "spellitemenchantmentcondition.dbc",
            "SpellItemEnchantmentCondition.dbc",
        ),
        (
            "gtoctclasscombatratingscalar.dbc",
            "gtOCTClassCombatRatingScalar.dbc",
        ),
        ("environmentaldamage.dbc", "EnvironmentalDamage.dbc"),
        ("material.dbc", "Material.dbc"),
        ("spellmechanic.dbc", "SpellMechanic.dbc"),
        ("gtoctregenhp.dbc", "gtOCTRegenHP.dbc"),
        ("exhaustion.dbc", "Exhaustion.dbc"),
        ("movie.dbc", "Movie.dbc"),
        ("spellmissile.dbc", "SpellMissile.dbc"),
        ("gtoctregenmp.dbc", "gtOCTRegenMP.dbc"),
        ("faction.dbc", "Faction.dbc"),
        ("moviefiledata.dbc", "MovieFileData.dbc"),
        ("spellmissilemotion.dbc", "SpellMissileMotion.dbc"),
        ("gtregenhpperspt.dbc", "gtRegenHPPerSpt.dbc"),
        ("factiongroup.dbc", "FactionGroup.dbc"),
        ("movievariation.dbc", "MovieVariation.dbc"),
        ("spellradius.dbc", "SpellRadius.dbc"),
        ("gtregenmpperspt.dbc", "gtRegenMPPerSpt.dbc"),
        ("factiontemplate.dbc", "FactionTemplate.dbc"),
        ("npcsounds.dbc", "NPCSounds.dbc"),
        ("spellrange.dbc", "SpellRange.dbc"),
        ("filedata.dbc", "FileData.dbc"),
        ("namegen.dbc", "NameGen.dbc"),
        ("spellrunecost.dbc", "SpellRuneCost.dbc"),
    ])
}
